#ISAQUE DE OLIVEIRA DOS SANTOS

GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo POST – Adicionar seu Cliente (USE SEUS DADOS AQUI)
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Isaque de Oliveira dos Santos",
    "cpf" : "123.456.789-00",
    "telefone" : "49999999999"
}

### Verbo PUT – Atualizar Cliente
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Isaque Santos",
    "cpf" : "123.456.789-00",
    "telefone" : "49888888888"
}

### Verbo DELETE - excluir cliente 1
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1