#ISAQUE DE OLIVEIRA DOS SANTOS
# URL base da API
@baseUrl = http://localhost:8000

@id = 7

### GET – Listar todos os produtos
GET {{baseUrl}}/produto/ HTTP/1.1

###
### GET – Buscar produto por ID
GET {{baseUrl}}/produto/{{id}} HTTP/1.1

###
### POST – Cadastrar novo produto
POST {{baseUrl}}/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "Bolacha Salgada",
    "descricao": "Salgada",
    "valor_unitario": 10.90
}

###
### POST – Cadastrar produto 2
POST {{baseUrl}}/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "Batata Frita Grande",
    "descricao": "Porção com molho da casa",
    "valor_unitario": 22.50
}

###
### POST – Cadastrar produto 3
POST {{baseUrl}}/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "Refrigerante Lata",
    "descricao": "Lata 350ml",
    "valor_unitario": 7.00
}

###
### PUT – Atualizar produto
PUT {{baseUrl}}/produto/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "Bolacha Doce",
    "descricao": "Doce",
    "valor_unitario": 12.00
}

###
### DELETE – Excluir produto
DELETE {{baseUrl}}/produto/{{id}} HTTP/1.1