#ISAQUE DE OLIVEIRA DOS SANTOS
# URL base da API
@baseUrl = http://localhost:8000

@id = 6

### GET – Listar todos os funcionários
GET {{baseUrl}}/funcionario/ HTTP/1.1

###
### GET – Buscar funcionário por ID
GET {{baseUrl}}/funcionario/{{id}} HTTP/1.1

###
### POST – Cadastrar novo funcionário
POST {{baseUrl}}/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Isaque Oliveira dos Santos",
    "matricula": "123455",
    "cpf": "11111111111",
    "telefone": "11999999999",
    "grupo": 1,
    "senha": "Admin123!"
}

###
### POST – Cadastrar funcionário 2
POST {{baseUrl}}/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Atendente Balcão",
    "matricula": "151695",
    "cpf": "22222222222",
    "telefone": "11988887777",
    "grupo": 2,
    "senha": "Balcao123!"
}

###
### POST – Cadastrar funcionário 3
POST {{baseUrl}}/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Atendente Caixa",
    "matricula": "151696",
    "cpf": "33333333333",
    "telefone": "11977776666",
    "grupo": 3,
    "senha": "Caixa123!"
}

###
### PUT – Atualizar funcionário
PUT {{baseUrl}}/funcionario/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "Isaque Oliveira",
    "matricula": "151516",
    "telefone": "49999471975",
    "senha": "novasenha123"
}

###
### DELETE – Excluir funcionário
DELETE {{baseUrl}}/funcionario/{{id}} HTTP/1.1